# Generated by Django 2.2.1 on 2020-02-13 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CiudadM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_civilM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='GeneroM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='OcupacionM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacion', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('apPat', models.CharField(max_length=254)),
                ('apMat', models.CharField(max_length=254)),
                ('edad', models.IntegerField()),
                ('delete', models.BooleanField(default=False)),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.CiudadM')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.EstadoM')),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Estado_civilM')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.GeneroM')),
                ('ocupacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.OcupacionM')),
            ],
            options={
                'db_table': 'ProfileP',
            },
        ),
    ]
