# Generated by Django 2.2.1 on 2020-02-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudadm',
            old_name='nombre',
            new_name='ciudad',
        ),
    ]
